config/routes.rb
Rails.application.routes.draw do
  resources :predictions
  devise_for :users
  resources :matches
  resources :clubs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'matches#index'

  resources :users do
    resources :predictions
  end
end

app/models/club.rb
# == Schema Information
#
# Table name: clubs
#
#  id         :bigint           not null, primary key
#  name       :string
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Club < ApplicationRecord
    has_many :clubs

    validates :name, presence: true
    validates :name, uniqueness: {case_sensitive: false}
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %i[ show edit update destroy ]

  # GET /clubs or /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1 or /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs or /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to club_url(@club), notice: "Club was successfully created." }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1 or /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to club_url(@club), notice: "Club was successfully updated." }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1 or /clubs/1.json
  def destroy
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url, notice: "Club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :score)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_club.html.erb
<div id="<%= dom_id club %>">
  <p>
    <strong>Name:</strong>
    <%= club.name %>
  </p>

</div>

app/views/clubs/_form.html.erb
<%= simple_form_for(@club) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render "form", club: @club %>

<br>

<div>
  <%= link_to "Show this club", @club %> |
  <%= link_to "Back to clubs", clubs_path %>
</div>

app/views/clubs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clubs</h1>

<div id="clubs">
  <% @clubs.each do |club| %>
    <%= render club %>
    <p>
      <%= link_to "Show this club", club %>
    </p>
  <% end %>
</div>

<%= link_to "New club", new_club_path %>

app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render "form", club: @club %>

<br>

<div>
  <%= link_to "Back to clubs", clubs_path %>
</div>

app/views/clubs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @club %>

<div>
  <%= link_to "Edit this club", edit_club_path(@club) %> |
  <%= link_to "Back to clubs", clubs_path %>

  <%= button_to "Destroy this club", @club, method: :delete %>
</div>