config/routes.rb
Rails.application.routes.draw do
  resources :predictions
  devise_for :users
  resources :matches
  resources :clubs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'matches#index'

  resources :users do
    resources :predictions
  end
end

app/models/prediction.rb
class Prediction < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :match, class_name: 'Match'

  validates :points, presence: true

  def match_label
    "L: #{match.local.name} vs V: #{match.visitor.name}"
  end

end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :set_prediction, only: %i[show edit update destroy]

  # GET /predictions or /predictions.json
  def index
    @predictions = Prediction.all
    @matches = Match.all
    @summary_points = User.all.map do |user|
      {
        email: user.email,
        points: user.predictions.pluck(:points).compact.reduce(:+)
      }
    end
    puts '..............................'
    puts @summary_points
  end

  # GET /predictions/1 or /predictions/1.json
  def show
    #   @user = User.new
    #   @prediction = Prediction.all
    #   if @user == @prediction.user
    #     puts prediction.user.email, prediction.points
    #   end
  end

  # GET /predictions/new
  def new
    @prediction = Prediction.new
  end

  # GET /predictions/1/edit
  def edit; end

  # POST /predictions or /predictions.json
  def create
    @prediction = Prediction.new(prediction_params)

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to prediction_url(@prediction), notice: 'Prediction was successfully created.' }
        format.json { render :show, status: :created, location: @prediction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predictions/1 or /predictions/1.json
  def update
    respond_to do |format|
      if @prediction.update(prediction_params)
        format.html { redirect_to prediction_url(@prediction), notice: 'Prediction was successfully updated.' }
        format.json { render :show, status: :ok, location: @prediction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1 or /predictions/1.json
  def destroy
    @prediction.destroy

    respond_to do |format|
      format.html { redirect_to predictions_url, notice: 'Prediction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_prediction
    @prediction = Prediction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def prediction_params
    params.require(:prediction).permit(:user_id, :bed, :match_id, :points)
  end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.erb
<%= simple_form_for(@prediction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user, label_method: :email %>
    <%= f.input :bed %>
    <%= f.association :match, label_method: :match_label %>
    <%= f.input :points %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/predictions/_prediction.html.erb
<div id="<%= dom_id prediction %>">
  <p>
    <strong>User:</strong>
    <%= prediction.user.email %>
  </p>

  <p>
    <strong>Bed:</strong>
    <%= prediction.bed %>
  </p>

  <p>
    <strong>Match:</strong>
    <%= prediction.match_label %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= prediction.points%>
  </p>

</div>

app/views/predictions/edit.html.erb
<h1>Editing prediction</h1>

<%= render "form", prediction: @prediction %>

<br>

<div>
  <%= link_to "Show this prediction", @prediction %> |
  <%= link_to "Back to predictions", predictions_path %>
</div>

app/views/predictions/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="index_predictions" style="display: flex">
<div id="predictions" style="display: grid">
<h1>Predictions</h1>

  <% @predictions.each do |prediction| %>
    <%= render prediction %>
    <p>
      <%= link_to "Show this prediction", prediction %>
    </p>
  <% end %>
</div>

<%= link_to "New prediction", new_prediction_path %>

  <div style="display: grid">
    <h2>Matches</h2>
      <% @matches.each do |match| %>
        <%= render match %>
      <%end%>
  </div>

  <div >
    <h2>Users</h2>
    <p>
      User: <%=@summary_points.first[:email]%>
    </p>
    <p>
      Points: <%=@summary_points.first[:points]%>
    </p>
  </div>
</div>

app/views/predictions/new.html.erb
<h1>New prediction</h1>

<%= render "form", prediction: @prediction %>

<br>

<div>
  <%= link_to "Back to predictions", predictions_path %>
</div>

app/views/predictions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @prediction %>


<div>
  <%= link_to "Edit this prediction", edit_prediction_path(@prediction) %> |
  <%= link_to "Back to predictions", predictions_path %>

  <%= button_to "Destroy this prediction", @prediction, method: :delete %>
</div>